// Rimato Admin Dashboard Data
export const rimatoDashboardData = {
  stats: {
    totalProjects: 24,
    activeProjects: 18,
    totalClients: 45,
    monthlyRevenue: 125000,
    teamMembers: 35,
    completionRate: 94,
  },
  recentProjects: [
    {
      id: "1",
      name: "Industriële reiniging productiehal",
      client: "Machinefabriek De Vries",
      status: "Lopend",
      priority: "Hoog",
      startDate: "2024-01-15",
      nextService: "2024-12-20",
      type: "Industriële reiniging",
      value: 8500,
      progress: 75,
      assignedTeam: ["Jan Smit", "Piet Bakker"],
    },
    {
      id: "2",
      name: "Periodiek rioolonderhoud",
      client: "Gemeente Hoogeveen",
      status: "Lopend",
      priority: "Normaal",
      startDate: "2023-06-01",
      nextService: "2024-12-15",
      type: "Rioolbeheer",
      value: 12000,
      progress: 60,
      assignedTeam: ["Klaas Visser", "Henk de Vries"],
    },
    {
      id: "3",
      name: "Gevelreiniging kantoorgebouw",
      client: "Hoogeveen Business Center",
      status: "Gepland",
      priority: "Laag",
      startDate: "2024-12-10",
      nextService: "2024-12-10",
      type: "Gevelbeheer",
      value: 4500,
      progress: 0,
      assignedTeam: ["Lisa Jansen"],
    },
    {
      id: "4",
      name: "Vloerreiniging magazijn",
      client: "Distributiecentrum Noord",
      status: "Lopend",
      priority: "Hoog",
      startDate: "2024-11-01",
      nextService: "2024-12-22",
      type: "Industriële reiniging",
      value: 6200,
      progress: 45,
      assignedTeam: ["Jan Smit"],
    },
  ],
  clients: [
    {
      id: "1",
      name: "Machinefabriek De Vries",
      contact: "Jan de Vries",
      email: "j.devries@machinefabriek.nl",
      phone: "0528-123456",
      status: "Actief",
      totalProjects: 8,
      totalValue: 45000,
      lastContact: "2024-12-10",
      type: "Industrieel",
    },
    {
      id: "2",
      name: "Gemeente Hoogeveen",
      contact: "Maria Jansen",
      email: "m.jansen@hoogeveen.nl",
      phone: "0528-789012",
      status: "Actief",
      totalProjects: 12,
      totalValue: 125000,
      lastContact: "2024-12-08",
      type: "Overheid",
    },
    {
      id: "3",
      name: "Hoogeveen Business Center",
      contact: "Peter Bakker",
      email: "p.bakker@hbc.nl",
      phone: "0528-345678",
      status: "Actief",
      totalProjects: 3,
      totalValue: 13500,
      lastContact: "2024-12-05",
      type: "Commercieel",
    },
  ],
  services: [
    {
      id: "1",
      name: "Industriële reiniging",
      description: "Vloeren, machines en productieruimtes",
      activeProjects: 12,
      monthlyRevenue: 65000,
      avgProjectValue: 5400,
    },
    {
      id: "2",
      name: "Rioolbeheer",
      description: "Inspectie, reiniging en onderhoud",
      activeProjects: 8,
      monthlyRevenue: 45000,
      avgProjectValue: 5600,
    },
    {
      id: "3",
      name: "Gevelbeheer",
      description: "Reiniging en onderhoud gevels",
      activeProjects: 4,
      monthlyRevenue: 15000,
      avgProjectValue: 3750,
    },
  ],
  revenue: {
    thisMonth: 125000,
    lastMonth: 118000,
    thisYear: 1450000,
    growth: 5.9,
  },
  upcomingTasks: [
    { id: "1", project: "Industriële reiniging productiehal", task: "Inspectie voorafgaand aan reiniging", dueDate: "2024-12-18", assignedTo: "Jan Smit" },
    { id: "2", project: "Periodiek rioolonderhoud", task: "Rapportage opstellen", dueDate: "2024-12-16", assignedTo: "Klaas Visser" },
    { id: "3", project: "Gevelreiniging kantoorgebouw", task: "Offerte voorbereiden", dueDate: "2024-12-15", assignedTo: "Lisa Jansen" },
  ],
};

// Neumann Admin Dashboard Data
export const neumannDashboardData = {
  stats: {
    totalClients: 28,
    activeClients: 18,
    totalSessions: 342,
    monthlyRevenue: 12500,
    avgSessionValue: 65,
    satisfactionRate: 4.8,
  },
  clients: [
    {
      id: "1",
      name: "Marijn Besseler",
      email: "marijn@example.nl",
      phone: "06-12345678",
      status: "Actief",
      goal: "Revalidatie knieblessure",
      startDate: "2024-03-01",
      nextSession: "2024-12-18",
      type: "1-op-1 Training",
      sessionsCompleted: 42,
      totalSessions: 50,
      progress: 84,
      package: "Revalidatie pakket",
      value: 3250,
    },
    {
      id: "2",
      name: "Kristel Kwant",
      email: "kristel@example.nl",
      phone: "06-23456789",
      status: "Actief",
      goal: "Hernia revalidatie & core stability",
      startDate: "2024-01-15",
      nextSession: "2024-12-19",
      type: "1-op-1 Training",
      sessionsCompleted: 58,
      totalSessions: 60,
      progress: 97,
      package: "Revalidatie pakket",
      value: 3900,
    },
    {
      id: "3",
      name: "Heather Court",
      email: "heather@example.nl",
      phone: "06-34567890",
      status: "Voltooid",
      goal: "Afvallen & kracht opbouwen",
      startDate: "2024-06-01",
      nextSession: null,
      type: "Online coaching",
      sessionsCompleted: 24,
      totalSessions: 24,
      progress: 100,
      package: "Online pakket",
      value: 1200,
    },
    {
      id: "4",
      name: "Fadil Deniz",
      email: "fadil@example.nl",
      phone: "06-45678901",
      status: "Actief",
      goal: "Explosiviteit voor kickboksen",
      startDate: "2024-08-10",
      nextSession: "2024-12-20",
      type: "1-op-1 Training",
      sessionsCompleted: 18,
      totalSessions: 30,
      progress: 60,
      package: "Performance pakket",
      value: 1950,
    },
  ],
  upcomingSessions: [
    { id: "1", client: "Marijn Besseler", date: "2024-12-18", time: "10:00", type: "1-op-1 Training", location: "Thuis" },
    { id: "2", client: "Kristel Kwant", date: "2024-12-19", time: "14:00", type: "1-op-1 Training", location: "Thuis" },
    { id: "3", client: "Fadil Deniz", date: "2024-12-20", time: "16:00", type: "1-op-1 Training", location: "Thuis" },
    { id: "4", client: "Sarah de Vries", date: "2024-12-21", time: "09:00", type: "Duo Training", location: "Park" },
  ],
  revenue: {
    thisMonth: 12500,
    lastMonth: 11800,
    thisYear: 145000,
    growth: 5.9,
  },
  services: [
    {
      id: "1",
      name: "1-op-1 Training aan huis",
      activeClients: 12,
      monthlyRevenue: 7800,
      avgSessionValue: 65,
      sessionsThisMonth: 120,
    },
    {
      id: "2",
      name: "Duo Personal Training",
      activeClients: 4,
      monthlyRevenue: 2400,
      avgSessionValue: 60,
      sessionsThisMonth: 40,
    },
    {
      id: "3",
      name: "Online coaching & voeding",
      activeClients: 8,
      monthlyRevenue: 1600,
      avgSessionValue: 200,
      sessionsThisMonth: 8,
    },
  ],
  recentReviews: [
    {
      name: "Erwin Altena",
      text: "De afgelopen 5 jaar heb ik Nick leren kennen als een enthousiaste jonge Personal Trainer die goed luistert naar de persoon die hij traint.",
      rating: 5,
      date: "2024-11-15",
    },
    {
      name: "Marijn Besseler",
      text: "Door een blessure aan mijn knie is het niet altijd makkelijk om te trainen maar Nick weet me altijd te motiveren om door te gaan.",
      rating: 5,
      date: "2024-11-20",
    },
  ],
};

