// Rimato Admin Dashboard Data
export const rimatoDashboardData = {
  stats: {
    totalProjects: 24,
    activeProjects: 18,
    totalClients: 45,
    monthlyRevenue: 125000,
    teamMembers: 35,
    completionRate: 94,
  },
  recentProjects: [
    {
      id: "1",
      name: "Industriële reiniging productiehal",
      client: "Machinefabriek De Vries",
      status: "Lopend",
      priority: "Hoog",
      startDate: "2024-01-15",
      nextService: "2024-12-20",
      type: "Industriële reiniging",
      value: 8500,
      progress: 75,
      assignedTeam: ["Jan Smit", "Piet Bakker"],
      description: "Grondige reiniging van productielijn en vloer met veiligheidsafzetting.",
      milestones: [
        { id: "m1", title: "Voorinspectie", date: "2024-01-10", done: true },
        { id: "m2", title: "Machine shutdown", date: "2024-01-15", done: true },
        { id: "m3", title: "Eindcontrole", date: "2024-01-16", done: false },
      ],
    },
    {
      id: "2",
      name: "Periodiek rioolonderhoud",
      client: "Gemeente Hoogeveen",
      status: "Lopend",
      priority: "Normaal",
      startDate: "2023-06-01",
      nextService: "2024-12-15",
      type: "Rioolbeheer",
      value: 12000,
      progress: 60,
      assignedTeam: ["Klaas Visser", "Henk de Vries"],
      description: "Jaarcontract inspectie, reiniging en rapportage van wijkriolering.",
      milestones: [
        { id: "m1", title: "Planning routes", date: "2024-12-05", done: true },
        { id: "m2", title: "Reiniging sector A", date: "2024-12-12", done: true },
        { id: "m3", title: "Rapportage opleveren", date: "2024-12-16", done: false },
      ],
    },
    {
      id: "3",
      name: "Gevelreiniging kantoorgebouw",
      client: "Hoogeveen Business Center",
      status: "Gepland",
      priority: "Laag",
      startDate: "2024-12-10",
      nextService: "2024-12-10",
      type: "Gevelbeheer",
      value: 4500,
      progress: 0,
      assignedTeam: ["Lisa Jansen"],
      description: "Stoomreiniging en nabehandeling met hydrofobe coating.",
      milestones: [
        { id: "m1", title: "Offerte akkoord", date: "2024-12-01", done: true },
        { id: "m2", title: "Materieel reserveren", date: "2024-12-08", done: true },
        { id: "m3", title: "Uitvoering", date: "2024-12-10", done: false },
      ],
    },
    {
      id: "4",
      name: "Vloerreiniging magazijn",
      client: "Distributiecentrum Noord",
      status: "Lopend",
      priority: "Hoog",
      startDate: "2024-11-01",
      nextService: "2024-12-22",
      type: "Industriële reiniging",
      value: 6200,
      progress: 45,
      assignedTeam: ["Jan Smit"],
      description: "Ontvetten en nabehandeling van betonnen vloeren in koelmagazijn.",
      milestones: [
        { id: "m1", title: "Voorinspectie", date: "2024-10-28", done: true },
        { id: "m2", title: "Uitvoering fase 1", date: "2024-11-02", done: true },
        { id: "m3", title: "Uitvoering fase 2", date: "2024-12-22", done: false },
      ],
    },
  ],
  leads: {
    offertegenerator: {
      disciplines: [
        { id: "industriel", name: "Industriële reiniging", basePrice: 1500, baseRate: 85, unit: "uur" },
        { id: "riool", name: "Rioolbeheer", basePrice: 1200, baseRate: 95, unit: "uur" },
        { id: "gevel", name: "Gevelbeheer", basePrice: 800, baseRate: 75, unit: "uur" },
      ],
      parameters: [
        { key: "oppervlakte_m2", label: "Oppervlakte (m²)" },
        { key: "vervuiling", label: "Type vervuiling" },
        { key: "uren", label: "Benodigde uren" },
        { key: "materiaal", label: "Materiaal kostprijs" },
      ],
    },
    intake: {
      sources: ["Webformulier", "E-mail", "Telefoon"],
      fields: [
        { key: "bedrijf", label: "Bedrijf" },
        { key: "contact", label: "Contactpersoon" },
        { key: "email", label: "E-mail" },
        { key: "telefoon", label: "Telefoon" },
        { key: "dienst", label: "Discipline" },
        { key: "beschrijving", label: "Korte omschrijving" },
      ],
    },
    pipeline: {
      stages: [
        { id: "nieuw", name: "Nieuw", description: "Nieuwe leads die nog gekwalificeerd moeten worden." },
        { id: "gekvalificeerd", name: "Gekwalificeerd", description: "Leads die voldoen aan de criteria en potentieel hebben." },
        { id: "offerte", name: "Offerte verzonden", description: "Offerte is verstuurd en wacht op reactie." },
        { id: "winst", name: "Winst", description: "Lead is omgezet naar een actief project." },
        { id: "verlies", name: "Verlies", description: "Lead is verloren gegaan (niet geconverteerd)." },
      ],
      leads: [
        {
          id: "L001",
          bedrijf: "Jansen B.V.",
          contact: "Jan Jansen",
          email: "j.jansen@jansenbv.nl",
          project: "Rioolreiniging kantoor",
          dienst: "Rioolbeheer",
          waarde: 8500,
          followUpDate: "2024-12-20",
          stageId: "nieuw",
        },
        {
          id: "L002",
          bedrijf: "Bakkerij Smits",
          contact: "Piet Smits",
          email: "p.smits@bakkerijsmits.nl",
          project: "Industriële ovenreiniging",
          dienst: "Industriële reiniging",
          waarde: 12000,
          followUpDate: "2024-12-22",
          stageId: "nieuw",
        },
        {
          id: "L003",
          bedrijf: "Gemeente Assen",
          contact: "Maria de Vries",
          email: "m.devries@assen.nl",
          project: "Gevelreiniging stadhuis",
          dienst: "Gevelbeheer",
          waarde: 15000,
          followUpDate: "2024-12-25",
          stageId: "gekvalificeerd",
        },
        {
          id: "L004",
          bedrijf: "Distributiecentrum Noord",
          contact: "Klaas Bakker",
          email: "k.bakker@dcnoord.nl",
          project: "Vloerreiniging magazijn",
          dienst: "Industriële reiniging",
          waarde: 9500,
          followUpDate: "2024-12-18",
          stageId: "offerte",
        },
        {
          id: "L005",
          bedrijf: "Metaalwarenfabriek BV",
          contact: "Lisa Jansen",
          email: "l.jansen@metaalwaren.nl",
          project: "Machine reiniging productielijn",
          dienst: "Industriële reiniging",
          waarde: 11000,
          followUpDate: "2024-12-15",
          stageId: "winst",
        },
        {
          id: "L006",
          bedrijf: "Hotel Intercontinental",
          contact: "Tom de Boer",
          email: "t.deboer@intercontinental.nl",
          project: "Gevelonderhoud",
          dienst: "Gevelbeheer",
          waarde: 18000,
          followUpDate: "2024-12-10",
          stageId: "verlies",
        },
      ],
    },
  },
  clients: [
    {
      id: "1",
      name: "Machinefabriek De Vries",
      contact: "Jan de Vries",
      email: "j.devries@machinefabriek.nl",
      phone: "0528-123456",
      status: "Actief",
      totalProjects: 8,
      totalValue: 45000,
      lastContact: "2024-12-10",
      type: "Industrieel",
    },
    {
      id: "2",
      name: "Gemeente Hoogeveen",
      contact: "Maria Jansen",
      email: "m.jansen@hoogeveen.nl",
      phone: "0528-789012",
      status: "Actief",
      totalProjects: 12,
      totalValue: 125000,
      lastContact: "2024-12-08",
      type: "Overheid",
    },
    {
      id: "3",
      name: "Hoogeveen Business Center",
      contact: "Peter Bakker",
      email: "p.bakker@hbc.nl",
      phone: "0528-345678",
      status: "Actief",
      totalProjects: 3,
      totalValue: 13500,
      lastContact: "2024-12-05",
      type: "Commercieel",
    },
  ],
  services: [
    {
      id: "1",
      name: "Industriële reiniging",
      description: "Vloeren, machines en productieruimtes",
      activeProjects: 12,
      monthlyRevenue: 65000,
      avgProjectValue: 5400,
    },
    {
      id: "2",
      name: "Rioolbeheer",
      description: "Inspectie, reiniging en onderhoud",
      activeProjects: 8,
      monthlyRevenue: 45000,
      avgProjectValue: 5600,
    },
    {
      id: "3",
      name: "Gevelbeheer",
      description: "Reiniging en onderhoud gevels",
      activeProjects: 4,
      monthlyRevenue: 15000,
      avgProjectValue: 3750,
    },
  ],
  revenue: {
    thisMonth: 125000,
    lastMonth: 118000,
    thisYear: 1450000,
    growth: 5.9,
  },
  upcomingTasks: [
    { id: "1", project: "Industriële reiniging productiehal", task: "Inspectie voorafgaand aan reiniging", dueDate: "2024-12-18", assignedTo: "Jan Smit" },
    { id: "2", project: "Periodiek rioolonderhoud", task: "Rapportage opstellen", dueDate: "2024-12-16", assignedTo: "Klaas Visser" },
    { id: "3", project: "Gevelreiniging kantoorgebouw", task: "Offerte voorbereiden", dueDate: "2024-12-15", assignedTo: "Lisa Jansen" },
  ],
};

// Neumann Admin Dashboard Data
export const neumannDashboardData = {
  stats: {
    totalClients: 28,
    activeClients: 18,
    totalSessions: 342,
    monthlyRevenue: 12500,
    avgSessionValue: 65,
    satisfactionRate: 4.8,
  },
  clients: [
    {
      id: "1",
      name: "Marijn Besseler",
      email: "marijn@example.nl",
      phone: "06-12345678",
      status: "Actief",
      goal: "Revalidatie knieblessure",
      startDate: "2024-03-01",
      nextSession: "2024-12-18",
      type: "1-op-1 Training",
      sessionsCompleted: 42,
      totalSessions: 50,
      progress: 84,
      package: "Revalidatie pakket",
      value: 3250,
    },
    {
      id: "2",
      name: "Kristel Kwant",
      email: "kristel@example.nl",
      phone: "06-23456789",
      status: "Actief",
      goal: "Hernia revalidatie & core stability",
      startDate: "2024-01-15",
      nextSession: "2024-12-19",
      type: "1-op-1 Training",
      sessionsCompleted: 58,
      totalSessions: 60,
      progress: 97,
      package: "Revalidatie pakket",
      value: 3900,
    },
    {
      id: "3",
      name: "Heather Court",
      email: "heather@example.nl",
      phone: "06-34567890",
      status: "Voltooid",
      goal: "Afvallen & kracht opbouwen",
      startDate: "2024-06-01",
      nextSession: null,
      type: "Online coaching",
      sessionsCompleted: 24,
      totalSessions: 24,
      progress: 100,
      package: "Online pakket",
      value: 1200,
    },
    {
      id: "4",
      name: "Fadil Deniz",
      email: "fadil@example.nl",
      phone: "06-45678901",
      status: "Actief",
      goal: "Explosiviteit voor kickboksen",
      startDate: "2024-08-10",
      nextSession: "2024-12-20",
      type: "1-op-1 Training",
      sessionsCompleted: 18,
      totalSessions: 30,
      progress: 60,
      package: "Performance pakket",
      value: 1950,
    },
  ],
  upcomingSessions: [
    { id: "1", client: "Marijn Besseler", date: "2024-12-18", time: "10:00", type: "1-op-1 Training", location: "Thuis" },
    { id: "2", client: "Kristel Kwant", date: "2024-12-19", time: "14:00", type: "1-op-1 Training", location: "Thuis" },
    { id: "3", client: "Fadil Deniz", date: "2024-12-20", time: "16:00", type: "1-op-1 Training", location: "Thuis" },
    { id: "4", client: "Sarah de Vries", date: "2024-12-21", time: "09:00", type: "Duo Training", location: "Park" },
  ],
  revenue: {
    thisMonth: 12500,
    lastMonth: 11800,
    thisYear: 145000,
    growth: 5.9,
  },
  services: [
    {
      id: "1",
      name: "1-op-1 Training aan huis",
      activeClients: 12,
      monthlyRevenue: 7800,
      avgSessionValue: 65,
      sessionsThisMonth: 120,
    },
    {
      id: "2",
      name: "Duo Personal Training",
      activeClients: 4,
      monthlyRevenue: 2400,
      avgSessionValue: 60,
      sessionsThisMonth: 40,
    },
    {
      id: "3",
      name: "Online coaching & voeding",
      activeClients: 8,
      monthlyRevenue: 1600,
      avgSessionValue: 200,
      sessionsThisMonth: 8,
    },
  ],
  recentReviews: [
    {
      name: "Erwin Altena",
      text: "De afgelopen 5 jaar heb ik Nick leren kennen als een enthousiaste jonge Personal Trainer die goed luistert naar de persoon die hij traint.",
      rating: 5,
      date: "2024-11-15",
    },
    {
      name: "Marijn Besseler",
      text: "Door een blessure aan mijn knie is het niet altijd makkelijk om te trainen maar Nick weet me altijd te motiveren om door te gaan.",
      rating: 5,
      date: "2024-11-20",
    },
  ],
};

// Vulcan Admin Dashboard Data
export const vulcanDashboardData = {
  stats: {
    totalInstallations: 156,
    activeInstallations: 142,
    totalClients: 89,
    monthlyRevenue: 45000,
    serviceCalls: 12,
    satisfactionRate: 4.9,
  },
  recentInstallations: [
    {
      id: "1",
      name: "Vulcan Residential - Hoofdwaterleiding",
      client: "Familie Jansen",
      status: "Actief",
      priority: "Normaal",
      installDate: "2024-11-15",
      nextService: "2025-11-15",
      type: "Residential Line",
      value: 1295,
      progress: 100,
      location: "Groningen",
      pipeDiameter: "20mm",
    },
    {
      id: "2",
      name: "Vulcan Commercial - Bedrijfsgebouw",
      client: "Hotel Intercontinental",
      status: "Actief",
      priority: "Hoog",
      installDate: "2024-10-20",
      nextService: "2025-10-20",
      type: "Commercial Line",
      value: 3495,
      progress: 100,
      location: "Amsterdam",
      pipeDiameter: "50mm",
    },
    {
      id: "3",
      name: "Vulcan Industrial - Productielijn",
      client: "Coca Cola Factory",
      status: "Actief",
      priority: "Hoog",
      installDate: "2024-09-10",
      nextService: "2025-09-10",
      type: "Industrial Line",
      value: 8995,
      progress: 100,
      location: "Rotterdam",
      pipeDiameter: "100mm",
    },
    {
      id: "4",
      name: "Vulcan Residential - Nieuwbouw",
      client: "Familie de Vries",
      status: "Gepland",
      priority: "Normaal",
      installDate: "2024-12-20",
      nextService: "2025-12-20",
      type: "Residential Line",
      value: 1295,
      progress: 0,
      location: "Utrecht",
      pipeDiameter: "20mm",
    },
  ],
  clients: [
    {
      id: "1",
      name: "Familie Jansen",
      contact: "Jan Jansen",
      email: "j.jansen@example.nl",
      phone: "06-12345678",
      status: "Actief",
      totalInstallations: 1,
      totalValue: 1295,
      lastContact: "2024-12-10",
      type: "Residentieel",
      location: "Groningen",
    },
    {
      id: "2",
      name: "Hotel Intercontinental",
      contact: "Peter Bakker",
      email: "p.bakker@intercontinental.nl",
      phone: "020-7890123",
      status: "Actief",
      totalInstallations: 3,
      totalValue: 10485,
      lastContact: "2024-12-08",
      type: "Commercieel",
      location: "Amsterdam",
    },
    {
      id: "3",
      name: "Coca Cola Factory",
      contact: "Maria Smit",
      email: "m.smit@cocacola.nl",
      phone: "010-3456789",
      status: "Actief",
      totalInstallations: 1,
      totalValue: 8995,
      lastContact: "2024-12-05",
      type: "Industrieel",
      location: "Rotterdam",
    },
  ],
  services: [
    {
      id: "1",
      name: "Residential Line",
      description: "Huishoudelijke installaties",
      activeInstallations: 98,
      monthlyRevenue: 127000,
      avgInstallationValue: 1295,
    },
    {
      id: "2",
      name: "Commercial Line",
      description: "Commerciële installaties",
      activeInstallations: 32,
      monthlyRevenue: 111840,
      avgInstallationValue: 3495,
    },
    {
      id: "3",
      name: "Industrial Line",
      description: "Industriële installaties",
      activeInstallations: 12,
      monthlyRevenue: 107940,
      avgInstallationValue: 8995,
    },
  ],
  revenue: {
    thisMonth: 45000,
    lastMonth: 42000,
    thisYear: 520000,
    growth: 7.1,
  },
  upcomingTasks: [
    { id: "1", project: "Vulcan Residential - Nieuwbouw", task: "Installatie afspraak", dueDate: "2024-12-20", assignedTo: "Installateur Team 1" },
    { id: "2", project: "Vulcan Commercial - Bedrijfsgebouw", task: "Jaarlijkse service check", dueDate: "2024-12-22", assignedTo: "Service Team" },
    { id: "3", project: "Vulcan Industrial - Productielijn", task: "Effectiviteitsrapportage", dueDate: "2024-12-18", assignedTo: "Technisch Team" },
  ],
  recentReviews: [
    {
      name: "Familie Jansen",
      text: "Na 2 weken was de kalkaanslag al merkbaar zachter en viel eruit. Na 6 maanden zijn alle leidingen schoon. Geweldig systeem!",
      rating: 5,
      date: "2024-11-20",
    },
    {
      name: "Hotel Intercontinental",
      text: "Het filter blijft nu schoon, wat normaal elke 48 uur vol zat met kalkafzettingen. Zeer tevreden met het resultaat.",
      rating: 5,
      date: "2024-10-25",
    },
  ],
};

