export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Important: Do not redefine <html>/<body> in nested layouts to avoid hydration mismatches
  // The root layout at src/app/layout.tsx already renders these tags.
  return children
}
